sudo: true
os: osx
osx_image: xcode10
rvm: system

install:
  - |
    # Force strict error checking.
    set -o errexit
    set -o pipefail
  - |
    # Mirror the repo as a tap.
    brew tap homebrew/cask
  - |
    # Switch to master branch.
    export HOMEBREW_COLOR=1
    export HOMEBREW_DEVELOPER=1
    export HOMEBREW_NO_AUTO_UPDATE=1
    brew update
  - brew install git || brew upgrade git || echo "git already installed"
  - brew install yarn p7zip

script:
  - bash ./jetbrains-cask-bot.sh
