sudo: true
os: osx
osx_image: xcode9.4
rvm: system

install:
    - |
        # Force strict error checking.
        set -o errexit
        set -o pipefail
    - |
        # Mirror the repo as a tap.
        brew tap homebrew/cask
    - |
        # Switch to master branch.
        export HOMEBREW_COLOR=1
        export HOMEBREW_DEVELOPER=1
        export HOMEBREW_NO_AUTO_UPDATE=1
        brew update
    - brew install yarn git p7zip

script:
    - bash ./jetbrains-cask-bot.sh
