sudo: true
os: osx
osx_image: xcode10.3
rvm: system

cache:
  directories:
    - /usr/local/Homebrew/Library/Homebrew/vendor/bundle
    - /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby

install:
  - |
    # Force strict error checking.
    set -o errexit
    set -o pipefail
  - |
    # Switch to master branch.
    export HOMEBREW_COLOR=1
    export HOMEBREW_DEVELOPER=1
    export HOMEBREW_NO_AUTO_UPDATE=1
    export HOMEBREW_NO_INSTALL_CLEANUP=1
    brew update-reset
    # Mirror the repo as a tap.
    brew tap homebrew/cask
    for formula in git coreutils findutils p7zip yarn; do
      brew install "$formula" || echo "$formula already installed"
    done
  - brew cask style mps
  - brew cask audit mps

script:
  - bash ./jetbrains-cask-bot.sh
