name: CI

on: [push]
#  schedule:
#    - cron: '13 * * * *'

jobs:
  check:
    runs-on: macOS-10.14
    env:
      HOMEBREW_COLOR: 1
      HOMEBREW_DEVELOPER: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
      HOMEBREW_NO_INSTALL_CLEANUP: 1
    steps:
      - uses: actions/checkout@v1
      - uses: actions/download-artifact@master
        continue-on-error: true
        with:
          name: previous-run
      - uses: ./.github/check-if-full-run
        id: checkIfFullRun
      - uses: actions/upload-artifact@master
        with:
          name: previous-run
          path: ./previous.json
      - name: Update Casks if neccessary
        if: steps.checkIfFullRun.outputs.run_full == 'yes'
        env:
          GIT_AUTHOR_EMAIL: jcb@leipert.io
          GIT_AUTHOR_NAME: jcbot
          GIT_COMMITTER_EMAIL: jcb@leipert.io
          GIT_COMMITTER_NAME: jcbot
          JCB_GITHUB_API_TOKEN: { { secrets.GITHUB_API_TOKEN } }
          JCB_PULLREQUEST_CC: '/cc @leipert'
          JCB_SOURCE_FORK_OWNER: leipert
          JCB_TARGET_OWNER: Homebrew
          JCB_TARGET_REPO: homebrew-cask
        shell: bash
        run: |
          set -o errexit
          set -o pipefail
          brew update-reset
          brew tap homebrew/cask
          for formula in git coreutils findutils p7zip yarn; do
            brew install "$formula" || echo "$formula already installed"
          done
          bash ./jetbrains-cask-bot.sh
