name: CI

on: [push]
#  schedule:
#    - cron: '13 * * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/download-artifact@master
        continue-on-error: true
        with:
          name: previous-run
      - uses: ./.github/check-if-full-run
        id: checkIfFullRun
      - name: Check if update is needed
        run: |
          ls -alth
          cat ./previous.json
          Triggering build: {{ toJson(steps.checkIfFullRun.outputs) }}
      - uses: actions/upload-artifact@master
        with:
          name: previous-run
          path: ./previous.json
#
#
#   updateCasks:
#     runs-on: macOS-10.14
#     env:
#       HOMEBREW_COLOR: 1
#       HOMEBREW_DEVELOPER: 1
#       HOMEBREW_NO_AUTO_UPDATE: 1
#       HOMEBREW_NO_INSTALL_CLEANUP: 1
#     steps:
#     - uses: actions/checkout@v1
#     - name: Install homebrew
#       shell: bash
#       run: |
#         set -o errexit
#         set -o pipefail
#         echo "HOMEBREW_NO_AUTO_UPDATE: $HOMEBREW_NO_AUTO_UPDATE"
#         echo "HOMEBREW_NO_INSTALL_CLEANUP: $HOMEBREW_NO_INSTALL_CLEANUP"
#         echo "Update homebrew"
#         brew update-reset
#         brew tap homebrew/cask
#         for formula in git coreutils findutils p7zip yarn; do
#           brew install "$formula" || echo "$formula already installed"
#         done
#         brew cask style mps
#         brew cask audit mps
#         bash ./jetbrains-cask-bot.sh
