name: CI

on: [push]
#  schedule:
#    - cron: '13 * * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: npm install, build, and test
      run: |
        npm ci
        node ./lib/has-update.js
        
# jobs:
#   check:
#     runs-on: linux
#     steps:
#     - uses: actions/checkout@v1
#     - uses: actions/download-artifact@master
#       with:
#         name: previous-run
#     - uses: actions/setup-node@v1.1.0
#       with:
#         node-version: '10.x'
#     - id: checkIfUpdateIsNeeded
#       name: Check if update is needed
#       run: |
#         npm install
#         node --version
#         node ./lib/has-update.js
#     - uses: actions/upload-artifact@master
#       with:
#         name: previous-run
#         path: ./previous.json
# 
#         
#   updateCasks:
#     runs-on: macOS-10.14
#     env:
#       HOMEBREW_COLOR: 1
#       HOMEBREW_DEVELOPER: 1
#       HOMEBREW_NO_AUTO_UPDATE: 1
#       HOMEBREW_NO_INSTALL_CLEANUP: 1
#     steps:
#     - uses: actions/checkout@v1
#     - name: Install homebrew
#       shell: bash
#       run: |
#         set -o errexit
#         set -o pipefail
#         echo "HOMEBREW_NO_AUTO_UPDATE: $HOMEBREW_NO_AUTO_UPDATE"
#         echo "HOMEBREW_NO_INSTALL_CLEANUP: $HOMEBREW_NO_INSTALL_CLEANUP"
#         echo "Update homebrew"
#         brew update-reset
#         brew tap homebrew/cask
#         for formula in git coreutils findutils p7zip yarn; do
#           brew install "$formula" || echo "$formula already installed"
#         done
#         brew cask style mps
#         brew cask audit mps
#         bash ./jetbrains-cask-bot.sh
