name: JetBrains Cask Bot

on:
  push:
    branches: '**'
  schedule:
    - cron: '*/30 * * * 1-5'
    - cron: '30 */4 * * 6,0'

jobs:
  beepboop:
    runs-on: macOS-10.14
    env:
      HOMEBREW_COLOR: 1
      HOMEBREW_DEVELOPER: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
      HOMEBREW_NO_INSTALL_CLEANUP: 1
    steps:
      - name: Checking out the latest version
        uses: actions/checkout@v1
      - uses: actions/cache@v1
        id: cache
        name: Cache previous.json
        with:
          path: tmp
          key: jcbot-v2
      - uses: ./.github/check-if-full-run
        name: Check if update is necessary
        id: checkIfFullRun
      - name: Run Update mechanism
        if: steps.checkIfFullRun.outputs.run_full == 'yes'
        shell: bash
        env:
          GIT_AUTHOR_EMAIL: jcb@leipert.io
          GIT_AUTHOR_NAME: jcbot
          GIT_COMMITTER_EMAIL: jcb@leipert.io
          GIT_COMMITTER_NAME: jcbot
          JCB_GITHUB_API_TOKEN: ${{ secrets.GITHUB_API_TOKEN }}
          JCB_PULLREQUEST_CC: '/cc @leipert'
          JCB_SOURCE_FORK_OWNER: leipert
          JCB_TARGET_OWNER: Homebrew
          JCB_TARGET_REPO: homebrew-cask
        run: |
          set -o errexit
          set -o pipefail
          brew update-reset
          brew tap homebrew/cask
          for formula in git coreutils findutils p7zip yarn; do
            brew install "$formula" || echo "$formula already installed"
          done
          bash ./jetbrains-cask-bot.sh
