name: JetBrains Cask Bot

on:
  push:
    branches: '**'
  schedule:
    - cron: '*/30 * * * *'

jobs:
  beepboop:
    runs-on: macOS-10.14
    steps:
    - uses: actions/checkout@v1
      name: Checking out the latest version
    - name: Run the bot
      run: |
        echo "Hello world"
        brew --version
